version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Taipei"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
      timezone: "Asia/Taipei"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
